# fly.toml app configuration file generated for delphi-site-delicate-dream-3507 on 2024-09-24T20:05:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'delphi-site-delicate-dream-3507'
primary_region = 'lax'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
